config/routes.rb
Rails.application.routes.draw do
  get '/auth/:provider/callback', to: 'users#facebook_login', as: :auth_callback
  get '/auth/failure', to: 'users#auth_failure', as: :auth_failure
  root 'static_pages#home'
  get '/home', to: 'static_pages#home'
  get '/search', to: 'static_pages#search'
  get '/signup', to: 'users#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  resources :users do
    member do
      get :following, :followers
    end

  end

  resources :microposts, only: [:new, :show, :create, :destroy] do
    resources :comments, only: [:create, :destroy]
  end
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :password_changes, only: [:edit, :update]
  resources :relationships, only: [:create, :destroy]
  resources :bookmarks, only: [:show, :create, :destroy]
  resources :notifications, only: [:index, :destroy]

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :logged_in_user, only: :search

  def home
    @feed_items = current_user.feed.paginate(page: params[:page]) if logged_in?
    @comment = current_user.comments.build if logged_in?
    if @feed_items.blank?
      @message = "ユーザーをフォローすると、フォローしたユーザーの投稿が表示されます"
    end
  end

  def search
    @comment = current_user.comments.build if logged_in?
    if params[:static_page][:search].present?
      microposts = Micropost.search(params[:static_page][:search]).paginate(page: params[:page])
      if microposts.any?
        @microposts = microposts
      else
        @microposts = Micropost.none.paginate(page: params[:page])
        @message = "条件に一致する投稿は見つかりませんでした"
      end
    else
      flash[:danger] = "検索ワードを入力してください"
      redirect_to request.referrer || root_url
    end
  end

end

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="row">
    <div class="col-xs-10 col-xs-offset-1 col-md-12 main-content">
      <h4><%= @message %></h4>
      <%= render 'shared/feed' %>
    </div>
  </div>
<% else %>
  <div class="row center">
    <div class="main-form col-6 col-xs-offset-3">
      <div class="box-1">
        <%= link_to image_tag("instagram.png", alt: "logo", width: "200px", class: "image_tag"), root_path %>

        <%= form_with(url: login_path, scope: :session, local: true) do |f| %>
          <%= f.email_field :email, class: 'form-control', placeholder: "メールアドレス" %>
          <%= f.password_field :password, class: 'form-control', placeholder: "パスワード" %>
          <%= f.submit "ログイン", class: "btn btn-primary" %>
        <% end %>

        <div class="title-border">または</div>

        <div class="facebook-login">
          <a href="/auth/facebook"><span class="fa fa-facebook-square"></span>Facebookでログイン</a>
        </div>
        
        <%= link_to "パスワードを忘れた場合", new_password_reset_path %>
      </div>

      <div class="box-2">
        <p class="align-items-center">アカウントをお持ちでないですか？ <%= link_to "登録する", signup_path %></p>
      </div>

      <p>ダウンロード</p>
      <%= link_to image_tag("appstore.png", alt: "logo", width: "150px"), "#" %>
      <%= link_to image_tag("googleplay.png", alt: "logo", width: "150px"), "#" %>
    </div>
  </div>
<%end%>

app/views/static_pages/search.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1 col-md-12 main-content">

    <h4><%= @message %></h4>

    <%# micropostのリストを推測して表示する %>
    <ol class="microposts">
      <%= render @microposts %>
    </ol>
    <%= will_paginate @microposts %>

  </div>
</div>