config/routes.rb
Rails.application.routes.draw do
  get '/auth/:provider/callback', to: 'users#facebook_login', as: :auth_callback
  get '/auth/failure', to: 'users#auth_failure', as: :auth_failure
  root 'static_pages#home'
  get '/home', to: 'static_pages#home'
  get '/search', to: 'static_pages#search'
  get '/signup', to: 'users#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  resources :users do
    member do
      get :following, :followers
    end

  end

  resources :microposts, only: [:new, :show, :create, :destroy] do
    resources :comments, only: [:create, :destroy]
  end
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :password_changes, only: [:edit, :update]
  resources :relationships, only: [:create, :destroy]
  resources :bookmarks, only: [:show, :create, :destroy]
  resources :notifications, only: [:index, :destroy]

end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  before_action :get_user,   only: [:edit, :update]
  before_action :valid_user, only: [:edit, :update]
  before_action :check_expiration, only: [:edit, :update] # パスワードの期限が切れていないか確認する

  def new
  end

  def create
    @user = User.find_by(email: params[:password_reset][:email].downcase)
    if @user
      if @user.uid.blank?
        @user.create_reset_digest # データベースにreset_digestを保存する
        @user.send_password_reset_email #パスワードリセットのメールをユーザーに送信する
        flash[:info] = "パスワードリセットのためのemailを送付しました"
        redirect_to root_url
      else
        flash[:info] = "パスワードを設定する必要はありません。Facebookアカウントを使ってログインしてください。"
        redirect_to root_url
      end
    else
      flash.now[:danger] = "一致するユーザーが見つかりませんでした"
      render 'new'
    end
  end

  def edit
  end

  def update
    if params[:user][:password].empty? # 新しいパスワードがblankだった場合
      @user.errors.add(:password, :blank) # パスワードがblankだった場合のエラーメッセージを追加する
      render 'edit'
    elsif @user.update(user_params) # 正しく更新できた場合
      log_in @user
      remember(@user)
      @user.update_attribute(:reset_digest, nil)
      flash[:success] = "パスワードが再設定されました"
      redirect_to @user
    else
      render 'edit' # パスワードが正しくない場合
    end
  end
  
  private

    def user_params
      params.require(:user).permit(:password, :password_confirmation)
    end

    def get_user
      @user = User.find_by(email: params[:email])
    end

    # 正しいユーザーかどうか確認する
    def valid_user
      unless (@user && @user.authenticated?(:reset, params[:id]))
        redirect_to root_url
      end
    end

    # トークンが期限切れかどうか確認する
    def check_expiration
      if @user.password_reset_expired?
        flash[:danger] = "パスワードの有効期限が切れています。"
        redirect_to new_password_reset_url
      end
    end

end

app/views/password_resets/edit.html.erb
<% provide(:title, 'パスワードの再設定') %>
<h1>パスワードの再設定</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @user, url: password_reset_path(params[:id]), local: true) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= hidden_field_tag :email, @user.email %>

      <%= f.label :"新しいパスワード" %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :"新しいパスワード(確認)" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "パスワードの更新", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/password_resets/new.html.erb
<% provide(:title, "パスワードをリセット") %>

<div class="row center">
  <div class="main-form col-6 col-xs-offset-3">
    <div class="box-password">
      <h4>パスワードのリセット</h4>
      <small class="sub-text">アカウントにアクセスするためのログインリンクを送信するため、メールアドレスを入力してください。</small>
      <div class="reset-form">
        <%= form_with(url: password_resets_path, scope: :password_reset, local: true) do |f| %>
          <%= f.label :"メールアドレス" %>
          <%= f.email_field :email, class: 'form-control' %>
          <%= f.submit "ログインリンクを送信", class: "btn btn-primary" %>
        <% end %>
      </div>
      <p>または</p>
      <%= link_to "新しいアカウントを作成", signup_path %>
    </div>
    <%= link_to "ログインに戻る", root_path, class: "btn btn-default login-btn" %>
  </div>
</div>