config/routes.rb
Rails.application.routes.draw do
  get '/auth/:provider/callback', to: 'users#facebook_login', as: :auth_callback
  get '/auth/failure', to: 'users#auth_failure', as: :auth_failure
  root 'static_pages#home'
  get '/home', to: 'static_pages#home'
  get '/search', to: 'static_pages#search'
  get '/signup', to: 'users#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  resources :users do
    member do
      get :following, :followers
    end

  end

  resources :microposts, only: [:new, :show, :create, :destroy] do
    resources :comments, only: [:create, :destroy]
  end
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :password_changes, only: [:edit, :update]
  resources :relationships, only: [:create, :destroy]
  resources :bookmarks, only: [:show, :create, :destroy]
  resources :notifications, only: [:index, :destroy]

end

app/controllers/password_changes_controller.rb
class PasswordChangesController < ApplicationController
  before_action :logged_in_user
  before_action :correct_user
  before_action :facebook_user

  def edit
  end

  def update
    if @user && @user.authenticate(params[:user][:current_password])
      if params[:user][:password].empty?
        redirect_to edit_password_change_path
        flash[:danger] = "新しいパスワードを正しく入力してください(6文字以上)"
      elsif @user.update(user_params)
        flash[:success] = "パスワードを変更しました"
        redirect_to @user
      else
        redirect_to edit_password_change_path
        flash[:danger] = "新しいパスワードを正しく入力してください(6文字以上)"  
      end
    else
      redirect_to edit_password_change_path
      flash[:danger] = "現在のパスワードが間違っています"
    end
  end

  private

    def user_params
      params.require(:user).permit(:password, :password_confirmation)
    end

    # 正しいユーザーかどうか確認
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    def facebook_user
      @user = User.find(params[:id])
      unless @user.uid.blank?
        flash[:info] = "パスワードを設定する必要はありません。Facebookアカウントを使用してください。"
        redirect_to request.referrer || root_url
      end  
    end

end

app/views/password_changes/edit.html.erb
<% provide(:title, 'パスワードを更新') %>
<% provide(:button_text, '更新') %>

<div class="row">
  <div class="col-xs-12">
  <%= render 'shared/edit_title' %>
      <%= form_with(model: @user, url: password_change_path, 
                                          method: :patch, local: true) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <div class="profile-box">
        <%= f.label :"現在のパスワード", class: "profile-name"%>
        <%= f.password_field :current_password, class: 'form-control' %>
      </div>

      <div class="profile-box">
        <%= f.label :"新しいパスワード", class: "profile-name" %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>
      
      <div class="profile-box">
        <%= f.label :"新しいパスワード(確認)", class: "profile-name" %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <div class="profile-btn">
        <%= f.submit yield(:button_text), class: "btn btn-primary" %>
        <%= link_to "プロフィールを編集する", edit_user_path(@user), class:"password-link" %>
      </div>
      
      <%= link_to "現在のパスワードが不明な場合", new_password_reset_path, class:"password-reset-link" %>

    <% end %>
  </div>
</div>