config/routes.rb
Rails.application.routes.draw do
  get '/auth/:provider/callback', to: 'users#facebook_login', as: :auth_callback
  get '/auth/failure', to: 'users#auth_failure', as: :auth_failure
  root 'static_pages#home'
  get '/home', to: 'static_pages#home'
  get '/search', to: 'static_pages#search'
  get '/signup', to: 'users#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  resources :users do
    member do
      get :following, :followers
    end

  end

  resources :microposts, only: [:new, :show, :create, :destroy] do
    resources :comments, only: [:create, :destroy]
  end
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :password_changes, only: [:edit, :update]
  resources :relationships, only: [:create, :destroy]
  resources :bookmarks, only: [:show, :create, :destroy]
  resources :notifications, only: [:index, :destroy]

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-offset-1 col-sm-9">
        <ul>
          <li><%= link_to "基本データ", '#' %></li>
          <li><%= link_to "ヘルプ", '#' %></li>
          <li><%= link_to "プレス", '#' %></li>
          <li><%= link_to "API", '#' %></li>
          <li><%= link_to "求人", '#' %></li>
          <li><%= link_to "プライバシー", '#' %></li>
          <li><%= link_to "利用規約", 'https://help.instagram.com/581066165581870' %></li>
          <li><%= link_to "所在地", '#' %></li>
          <li><%= link_to "人気アカウント", '#' %></li>
          <li><%= link_to "ハッシュタグ", '#' %></li>
          <li><%= link_to "言語", '#' %></li>
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<% if logged_in? %>
<header class="navbar navbar-fixed-top">
  <div class="container">
    <div class="row">
      <div class="col-xs-3">
        <%= link_to image_tag("instagram.png", alt: "logo", width: "100px", id: "logo"), root_path %>
      </div>
      <nav class="col-xs-9">
        <div class="nav navbar-nav hidden-xs">
          <%= form_with(class: "search-form",  url: search_path, scope: :static_page, 
                                                  method: :get, local: true) do |f| %>
            <%= f.text_field :search, class: "form-control", placeholder: "検索" %>
            <%= f.submit '検索', class: "form-btn" %>
          <% end %>
        </div>
        <ul class="nav navbar-nav navbar-right">
          <li>
            <%= link_to root_path do %>
              <span class= "fa fa-home fa-lg"></span>
            <%end%>
          </li>
          <li>
            <%= link_to new_micropost_path do %>
              <span class= "fa fa-plus-square-o fa-lg"></span>
            <%end%>
          </li>
          <li>
            <%= link_to users_path do %>
              <span class= "fa fa-address-book-o fa-lg"></span>
            <%end%>
          </li>
          <li>
            <%= link_to notifications_path do %>
              <span class= "fa fa-heart-o fa-lg"></span>
              <% if unchecked_notifications.any? %> 
                <span class="fa fa-circle"></span>
              <% end %> 
            <%end%>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <span class= "fa fa-user-circle-o fa-lg"></span><b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "プロフィール", current_user %></li>
              <li><%= link_to "保存済み", bookmark_path(current_user) %></li>
              <li><%= link_to "設定", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "ログアウト", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        </ul>
      </nav>
    </div>
  </div>
</header>
<% else %>
<% end %>

app/views/layouts/_shim.html.erb
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application',
                               'data-turbolinks-track': 'reload' %>
    <%=render 'layouts/shim'%>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="description" content="インスタグラムのコピーサイトです。画像の投稿ができる簡易的なSNSです。">
    <meta name="keywords" content="コピーサイト, ポートフォリオ, エンジニア初心者, インスタグラム">
    <%= favicon_link_tag('favicon.ico') %>
    <%= analytics_init if Rails.env.production? %>
  </head>
  <body>
    <%=render 'layouts/header'%>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%=render 'layouts/footer'%>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>